In [13]:
import pandas as pd
from sklearn.model_selection import train_test_split
from tqdm import tqdm
from skmultilearn.model_selection import iterative_train_test_split
import numpy as np
import csv

In [14]:
class_names = ['5_o_Clock_Shadow', 'Arched_Eyebrows', 'Attractive', 'Bags_Under_Eyes', 'Bald', 'Bangs',
                                'Big_Lips', 'Big_Nose', 'Black_Hair', 'Blond_Hair', 'Blurry', 'Brown_Hair', 'Bushy_Eyebrows',      
                                'Chubby', 'Double_Chin', 'Eyeglasses', 'Goatee', 'Gray_Hair', 'Heavy_Makeup', 'High_Cheekbones',       
                                'Male', 'Mouth_Slightly_Open', 'Mustache', 'Narrow_Eyes', 'No_Beard', 'Oval_Face', 'Pale_Skin', 
                                'Pointy_Nose', 'Receding_Hairline', 'Rosy_Cheeks', 'Sideburns', 'Smiling', 'Straight_Hair', 'Wavy_Hair', 
                                'Wearing_Earrings', 'Wearing_Hat', 'Wearing_Lipstick', 'Wearing_Necklace', 'Wearing_Necktie', 'Young']
       

In [15]:
dirname = "/scratch/mariamma/celeba/data/celeba/"
df = pd.read_csv(dirname+"/list_attr_celeba.csv",delimiter="\s+", index_col=False)
df = df.replace(-1, 0)
print(df.head())

        Image  5_o_Clock_Shadow  Arched_Eyebrows  Attractive  Bags_Under_Eyes  \
0  000001.jpg                 0                1           1                0   
1  000002.jpg                 0                0           0                1   
2  000003.jpg                 0                0           0                0   
3  000004.jpg                 0                0           1                0   
4  000005.jpg                 0                1           1                0   

   Bald  Bangs  Big_Lips  Big_Nose  Black_Hair  ...  Sideburns  Smiling  \
0     0      0         0         0           0  ...          0        1   
1     0      0         0         1           0  ...          0        1   
2     0      0         1         0           0  ...          0        0   
3     0      0         0         0           0  ...          0        0   
4     0      0         1         0           0  ...          0        0   

   Straight_Hair  Wavy_Hair  Wearing_Earrings  Wearing_Hat  We

In [16]:
fileDescriptor = open(dirname+'/list_eval_partition.txt', "r")
        #---- get into the loop
file_list = []        
line = True
for i in tqdm(range(202599)):
        line = fileDescriptor.readline()
        line = line.strip()
        line = line.split(" ")      
        if int(line[1]) == 2:
                file_list.append(line[0])
print(len(file_list))                                

100%|██████████| 202599/202599 [00:00<00:00, 481091.92it/s]

19962


In [17]:
df_sub = df[df['Image'].isin(file_list)]
df_sub.shape

(19962, 41)

In [18]:
df_sub.head()

Image  5_o_Clock_Shadow  Arched_Eyebrows  Attractive  \
182637  182638.jpg                 0                1           0   
182638  182639.jpg                 0                0           0   
182639  182640.jpg                 0                0           1   
182640  182641.jpg                 0                0           1   
182641  182642.jpg                 0                0           0   

        Bags_Under_Eyes  Bald  Bangs  Big_Lips  Big_Nose  Black_Hair  ...  \
182637                1     0      0         0         0           0  ...   
182638                0     0      0         0         1           1  ...   
182639                0     0      0         0         0           0  ...   
182640                0     0      0         0         0           0  ...   
182641                0     0      0         0         0           1  ...   

        Sideburns  Smiling  Straight_Hair  Wavy_Hair  Wearing_Earrings  \
182637          0        1              0          1                 1   
182638          0        0              0          1                 0   
182639          0        1              0          1                 0   
182640          0        1              0          0                 1   
182641          0        1              0          0                 0   

        Wearing_Hat  Wearing_Lipstick  Wearing_Necklace  Wearing_Necktie  \
182637            1                 0                 0                0   
182638            0                 1                 0                0   
182639            0                 1                 0                0   
182640            0                 1                 0                0   
182641            0                 0                 0                0   

        Young  
182637      0  
182638      1  
182639      1  
182640      1  
182641      1  

[5 rows x 41 columns]

In [19]:
df_sub.describe()

5_o_Clock_Shadow  Arched_Eyebrows    Attractive  Bags_Under_Eyes  \
count      19962.000000     19962.000000  19962.000000     19962.000000   
mean           0.099890         0.284440      0.495842         0.202635   
std            0.299861         0.451159      0.499995         0.401973   
min            0.000000         0.000000      0.000000         0.000000   
25%            0.000000         0.000000      0.000000         0.000000   
50%            0.000000         0.000000      0.000000         0.000000   
75%            0.000000         1.000000      1.000000         0.000000   
max            1.000000         1.000000      1.000000         1.000000   

               Bald         Bangs      Big_Lips      Big_Nose    Black_Hair  \
count  19962.000000  19962.000000  19962.000000  19962.000000  19962.000000   
mean       0.021190      0.155746      0.327021      0.212003      0.271616   
std        0.144022      0.362623      0.469137      0.408737      0.444804   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        0.000000      0.000000      0.000000      0.000000      0.000000   
50%        0.000000      0.000000      0.000000      0.000000      0.000000   
75%        0.000000      0.000000      1.000000      0.000000      1.000000   
max        1.000000      1.000000      1.000000      1.000000      1.000000   

         Blond_Hair  ...     Sideburns       Smiling  Straight_Hair  \
count  19962.000000  ...  19962.000000  19962.000000   19962.000000   
mean       0.133253  ...      0.046388      0.500301       0.209899   
std        0.339857  ...      0.210329      0.500012       0.407246   
min        0.000000  ...      0.000000      0.000000       0.000000   
25%        0.000000  ...      0.000000      0.000000       0.000000   
50%        0.000000  ...      0.000000      1.000000       0.000000   
75%        0.000000  ...      0.000000      1.000000       0.000000   
max        1.000000  ...      1.000000      1.000000       1.000000   

          Wavy_Hair  Wearing_Earrings   Wearing_Hat  Wearing_Lipstick  \
count  19962.000000      19962.000000  19962.000000      19962.000000   
mean       0.364042          0.206643      0.042030          0.521892   
std        0.481172          0.404907      0.200662          0.499533   
min        0.000000          0.000000      0.000000          0.000000   
25%        0.000000          0.000000      0.000000          0.000000   
50%        0.000000          0.000000      0.000000          1.000000   
75%        1.000000          0.000000      0.000000          1.000000   
max        1.000000          1.000000      1.000000          1.000000   

       Wearing_Necklace  Wearing_Necktie         Young  
count      19962.000000     19962.000000  19962.000000  
mean           0.137912         0.070083      0.757139  
std            0.344816         0.255294      0.428823  
min            0.000000         0.000000      0.000000  
25%            0.000000         0.000000      1.000000  
50%            0.000000         0.000000      1.000000  
75%            0.000000         0.000000      1.000000  
max            1.000000         1.000000      1.000000  

[8 rows x 40 columns]

In [20]:
X = df_sub[['Image']].to_numpy()
y = df_sub[class_names].to_numpy()
print(X,y)

[['182638.jpg']
 ['182639.jpg']
 ['182640.jpg']
 ...
 ['202597.jpg']
 ['202598.jpg']
 ['202599.jpg']] [[0 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 [0 0 1 ... 0 0 1]
 ...
 [0 0 0 ... 0 0 1]
 [0 1 1 ... 0 0 1]
 [0 1 1 ... 0 0 1]]


In [9]:
X_train, X_test, y_train, y_test = iterative_train_test_split(X, y,
                                                    test_size=0.10)

In [28]:
len(y_train)

2070

In [24]:
y_train[2069]

array(['202341.jpg'], dtype=object)

In [27]:
y_train

array([['182641.jpg'],
       ['182642.jpg'],
       ['182643.jpg'],
       ...,
       ['201419.jpg'],
       ['202204.jpg'],
       ['202341.jpg']], dtype=object)

In [21]:
y_train.tofile("out.txt")

OSError: cannot write object arrays to a file in binary mode

In [ ]:
wtr = csv.writer(open('out2.csv', 'w'), lineterminator='\n')
for i in range(len(y_train)) : 
    print(i)
    wtr.writerow(y_train[i])