In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from tqdm import tqdm
from skmultilearn.model_selection import iterative_train_test_split
import numpy as np
import csv

In [28]:
filename = "/scratch/mariamma/xraysetu/dataset/val_1.txt"
df = pd.read_csv(filename, delimiter = " ", header=None)
df.head()

0   1   2   3   4   5   6   7   8   9   10  11  \
0  images_012/00028178_000.png   0   0   0   0   0   0   0   0   0   0   0   
1  images_012/00030605_000.png   0   0   0   1   0   0   0   0   0   0   0   
2  images_005/00011297_000.png   0   0   0   0   0   0   0   0   0   0   0   
3  images_005/00011297_001.png   0   0   0   0   0   0   0   0   0   0   0   
4  images_008/00016540_000.png   0   0   0   0   0   0   0   0   0   0   0   

   12  13  14  
0   0   0   0  
1   0   0   0  
2   0   0   0  
3   0   0   0  
4   0   0   0

In [29]:
class_names = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
X = df[[0]].to_numpy()
y = df[class_names].to_numpy()
print(X,y)

[['images_012/00028178_000.png']
 ['images_012/00030605_000.png']
 ['images_005/00011297_000.png']
 ...
 ['images_011/00025128_006.png']
 ['images_011/00025128_007.png']
 ['images_011/00025128_008.png']] [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [30]:
X_train, X_test, y_train, y_test = iterative_train_test_split(X, y,
                                                    test_size=0.20)

In [31]:
len(y_train)

2244

In [32]:
y_train

array([['images_012/00030605_000.png'],
       ['images_004/00008473_002.png'],
       ['images_004/00008473_004.png'],
       ...,
       ['images_003/00004805_000.png'],
       ['images_008/00016067_000.png'],
       ['images_010/00023006_000.png']], dtype=object)

In [34]:
wtr = csv.writer(open('out2.csv', 'w'), lineterminator='\n')
for i in range(len(y_train)) : 
    print(i)
    wtr.writerow(y_train[i])

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
27

In [7]:
y_train

array([['images_012/00030605_000.png'],
       ['images_004/00008473_002.png'],
       ['images_004/00008473_009.png'],
       ...,
       ['images_008/00016170_000.png'],
       ['images_011/00025128_003.png'],
       ['images_011/00025128_006.png']], dtype=object)

In [35]:
y_train = np.reshape(y_train, -1)
y_train

array(['images_012/00030605_000.png', 'images_004/00008473_002.png',
       'images_004/00008473_004.png', ..., 'images_003/00004805_000.png',
       'images_008/00016067_000.png', 'images_010/00023006_000.png'],
      dtype=object)

In [64]:
df_sub = df[df[0].isin(y_train)]
df_sub

0   1   2   3   4   5   6   7   8   9   10  \
1      images_012/00030605_000.png   0   0   0   1   0   0   0   0   0   0   
8      images_004/00008473_002.png   0   0   0   0   0   0   0   0   0   0   
10     images_004/00008473_004.png   0   0   0   0   0   0   0   1   0   0   
15     images_004/00008473_009.png   0   0   0   1   0   0   0   0   0   0   
18     images_004/00008473_012.png   0   0   0   0   0   0   0   0   0   0   
...                            ...  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..   
11197  images_004/00007512_002.png   0   0   0   0   0   0   0   0   0   0   
11200  images_001/00000990_000.png   0   0   0   0   0   0   0   0   0   0   
11201  images_003/00004805_000.png   0   0   0   0   0   0   0   0   0   0   
11203  images_008/00016067_000.png   0   0   0   0   0   0   0   0   0   0   
11207  images_010/00023006_000.png   0   0   0   0   0   0   0   0   0   0   

       11  12  13  14  
1       0   0   0   0  
8       1   0   0   0  
10      0   0   0   0  
15      0   0   0   0  
18      0   0   1   0  
...    ..  ..  ..  ..  
11197   0   0   0   0  
11200   0   0   0   0  
11201   0   0   0   0  
11203   0   0   0   0  
11207   0   0   0   0  

[2244 rows x 15 columns]

In [65]:
for i in range(15):
    print(df[i].sum(), df_sub[i].sum())

images_012/00028178_000.pngimages_012/00030605_000.pngimages_005/00011297_000.pngimages_005/00011297_001.pngimages_008/00016540_000.pngimages_009/00018696_000.pngimages_004/00008473_000.pngimages_004/00008473_001.pngimages_004/00008473_002.pngimages_004/00008473_003.pngimages_004/00008473_004.pngimages_004/00008473_005.pngimages_004/00008473_006.pngimages_004/00008473_007.pngimages_004/00008473_008.pngimages_004/00008473_009.pngimages_004/00008473_010.pngimages_004/00008473_011.pngimages_004/00008473_012.pngimages_012/00029436_000.pngimages_010/00024149_000.pngimages_009/00020464_000.pngimages_010/00023835_000.pngimages_003/00005872_000.pngimages_003/00005872_001.pngimages_003/00005872_002.pngimages_010/00023972_000.pngimages_010/00023704_000.pngimages_006/00013281_000.pngimages_004/00008031_000.pngimages_008/00017498_000.pngimages_010/00022306_000.pngimages_002/00001652_000.pngimages_002/00001652_001.pngimages_010/00022281_000.pngimages_007/00015787_000.pngimages_009/00018872_000.pngi

In [66]:
cnt = 0
class_names = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
for i in range(df_sub.shape[0]):
    sum = 0
    for j in class_names:
        sum += df.iloc[i][j]
    if sum == 0:
        cnt += 1
print(cnt)          

1279


In [67]:
df_sub_new2 = pd.DataFrame(columns=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14])
class_names = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
cnt = 0
for idx, row in df_sub.iterrows():
    sum = 0
    for j in class_names:
        sum += row[j]
    if sum == 0:
        cnt += 1
        if cnt < 479:
            df_sub_new2 = pd.concat((df_sub_new2, pd.DataFrame([row])),  ignore_index=True)
    else:
        df_sub_new2 = pd.concat((df_sub_new2, pd.DataFrame([row])), ignore_index=True)
print(df_sub_new2.shape)
print(df_sub_new2.head())

(1500, 15)
                            0  1  2  3  4  5  6  7  8  9  10 11 12 13 14
0  images_012/00030605_000.png  0  0  0  1  0  0  0  0  0  0  0  0  0  0
1  images_004/00008473_002.png  0  0  0  0  0  0  0  0  0  0  1  0  0  0
2  images_004/00008473_004.png  0  0  0  0  0  0  0  1  0  0  0  0  0  0
3  images_004/00008473_009.png  0  0  0  1  0  0  0  0  0  0  0  0  0  0
4  images_004/00008473_012.png  0  0  0  0  0  0  0  0  0  0  0  0  1  0


In [68]:
for i in range(1,15):
    print(df[i].sum(), df_sub_new2[i].sum())

1119 224
240 48
1292 258
2018 404
625 125
613 123
133 27
504 101
447 89
200 40
208 42
166 33
372 74
41 8


In [69]:
for i in range(1,15):
    print(df[i].sum(), df_sub_new2[i].sum())

1119 224
240 48
1292 258
2018 404
625 125
613 123
133 27
504 101
447 89
200 40
208 42
166 33
372 74
41 8


In [73]:
df_sub_new2.to_csv("nih_val_short.csv", index=False, header=False,sep=" ")

In [2]:
df_topk = pd.read_csv("/data/mariammaa/nih_multi_label/topk_image_iter.csv")
df_topk.head()

Unnamed: 0     imagename  iter
0           0  00028178_000     7
1           1  00030605_000    16
2           2  00011297_000    16
3           3  00011297_001    16
4           4  00016540_000    40

In [22]:
df = pd.read_csv("nih_val_short.csv", sep=" ", header=None)
df.head()


0   1   2   3   4   5   6   7   8   9   10  11  \
0  images_012/00030605_000.png   0   0   0   1   0   0   0   0   0   0   0   
1  images_004/00008473_002.png   0   0   0   0   0   0   0   0   0   0   1   
2  images_004/00008473_004.png   0   0   0   0   0   0   0   1   0   0   0   
3  images_004/00008473_009.png   0   0   0   1   0   0   0   0   0   0   0   
4  images_004/00008473_012.png   0   0   0   0   0   0   0   0   0   0   0   

   12  13  14  
0   0   0   0  
1   0   0   0  
2   0   0   0  
3   0   0   0  
4   0   1   0

In [28]:
file_lst =df[0].to_list()
cnt = 0
class_names = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
normal_cnt = 0
for x in file_lst:
    file_name = x.split("/")[-1]
    file_name = file_name.replace(".png", "")
    rows = df_topk[df_topk['imagename'] == file_name]
    
    if rows['iter'].to_list()[0] == 0:
        df_sub = df[df[0] == x]
        print(df_sub)
        # print(rows)
        cnt += 1
        sum = 0
        for idx, row in df_sub.iterrows():
            for j in class_names:
                sum += row[j]
            if sum == 0:
                normal_cnt += 1

print(cnt, normal_cnt)        

                            0   1   2   3   4   5   6   7   8   9   10  11  \
2  images_004/00008473_004.png   0   0   0   0   0   0   0   1   0   0   0   

   12  13  14  
2   0   0   0  
                             0   1   2   3   4   5   6   7   8   9   10  11  \
21  images_005/00011379_043.png   0   0   1   0   1   1   0   0   1   0   0   

    12  13  14  
21   0   0   0  
                             0   1   2   3   4   5   6   7   8   9   10  11  \
32  images_009/00018686_002.png   0   0   1   0   0   0   0   0   0   0   0   

    12  13  14  
32   0   0   0  
                             0   1   2   3   4   5   6   7   8   9   10  11  \
41  images_006/00013300_001.png   0   0   1   1   0   0   0   0   0   0   0   

    12  13  14  
41   0   0   0  
                             0   1   2   3   4   5   6   7   8   9   10  11  \
42  images_006/00011849_002.png   1   0   0   0   0   0   0   0   0   0   0   

    12  13  14  
42   0   0   0  
                             0   1   2 

In [11]:
df_topk = pd.read_csv("/data/mariammaa/nih_multi_label/topk_image_iter.csv")
df_topk_sub = df_topk[df_topk['iter'] > 0]
df_topk_sub.head()

Unnamed: 0     imagename  iter
0           0  00028178_000     7
1           1  00030605_000    16
2           2  00011297_000    16
3           3  00011297_001    16
4           4  00016540_000    40

In [3]:
filename = "/scratch/mariamma/xraysetu/dataset/val_1.txt"
df_val = pd.read_csv(filename, delimiter = " ", header=None)
df_val.head()

0   1   2   3   4   5   6   7   8   9   10  11  \
0  images_012/00028178_000.png   0   0   0   0   0   0   0   0   0   0   0   
1  images_012/00030605_000.png   0   0   0   1   0   0   0   0   0   0   0   
2  images_005/00011297_000.png   0   0   0   0   0   0   0   0   0   0   0   
3  images_005/00011297_001.png   0   0   0   0   0   0   0   0   0   0   0   
4  images_008/00016540_000.png   0   0   0   0   0   0   0   0   0   0   0   

   12  13  14  
0   0   0   0  
1   0   0   0  
2   0   0   0  
3   0   0   0  
4   0   0   0

In [ ]:
df_val_new = pd.DataFrame()
for idx, row in df_val.iterrows():
    row[0] = row[0].split("/")[-1]
    df_val_new = pd.concat((df_val_new, pd.DataFrame([row])),  ignore_index=True)
df_val_new.head()

0   1   2   3   4   5   6   7   8   9   10  11  12  13  14
0  00028178_000.png   0   0   0   0   0   0   0   0   0   0   0   0   0   0
1  00030605_000.png   0   0   0   1   0   0   0   0   0   0   0   0   0   0
2  00011297_000.png   0   0   0   0   0   0   0   0   0   0   0   0   0   0
3  00011297_001.png   0   0   0   0   0   0   0   0   0   0   0   0   0   0
4  00016540_000.png   0   0   0   0   0   0   0   0   0   0   0   0   0   0

In [12]:
df_topk_sub['imagename'] = df_topk_sub['imagename'] + ".png"
topk_filelist = df_topk_sub['imagename'].to_list()
df_val_sub = df_val_new[df_val_new[0].isin(topk_filelist)]
print(df_val_sub.shape)
df_val_sub.head()

(9978, 15)


/tmp/ipykernel_397666/3912908956.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_topk_sub['imagename'] = df_topk_sub['imagename'] + ".png"


0   1   2   3   4   5   6   7   8   9   10  11  12  13  14
0  00028178_000.png   0   0   0   0   0   0   0   0   0   0   0   0   0   0
1  00030605_000.png   0   0   0   1   0   0   0   0   0   0   0   0   0   0
2  00011297_000.png   0   0   0   0   0   0   0   0   0   0   0   0   0   0
3  00011297_001.png   0   0   0   0   0   0   0   0   0   0   0   0   0   0
4  00016540_000.png   0   0   0   0   0   0   0   0   0   0   0   0   0   0

In [13]:
for i in range(1,15):
    print(df_val[i].sum(), df_val_sub[i].sum())

1119 907
240 219
1292 985
2018 1712
625 502
613 529
133 113
504 414
447 357
200 161
208 158
166 156
372 310
41 37


In [14]:
df = df_val_sub
class_names = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
X = df[[0]].to_numpy()
y = df[class_names].to_numpy()
print(X,y)

[['00028178_000.png']
 ['00030605_000.png']
 ['00011297_000.png']
 ...
 ['00025128_005.png']
 ['00025128_007.png']
 ['00025128_008.png']] [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [15]:
X_train, X_test, y_train, y_test = iterative_train_test_split(X, y,
                                                    test_size=0.20)

In [16]:
y_train = np.reshape(y_train, -1)
y_train

array(['00018696_000.png', '00008473_002.png', '00008473_008.png', ...,
       '00023006_000.png', '00016170_000.png', '00017510_000.png'],
      dtype=object)

In [22]:
df_sub = df[df[0].isin(y_train)]
df_sub.shape

(1996, 15)

In [18]:
for i in range(1,15):
    print(df[i].sum(), df_sub[i].sum())

907 181
219 44
985 197
1712 342
502 100
529 106
113 23
414 83
357 71
161 32
158 32
156 31
310 62
37 7


In [21]:
cnt = 0
class_names = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
for i in range(df_sub.shape[0]):
    sum = 0
    for j in class_names:
        sum += df_sub.iloc[i][j]
    if sum == 0:
        cnt += 1
print(cnt)          

1143


In [30]:
df_sub_new2 = pd.DataFrame(columns=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14])
class_names = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
cnt = 0
for idx, row in df_sub.iterrows():
    sum = 0
    for j in class_names:
        sum += row[j]
    if sum == 0:
        cnt += 1
        if cnt <= 647:
            df_sub_new2 = pd.concat((df_sub_new2, pd.DataFrame([row])),  ignore_index=True)
    else:
        df_sub_new2 = pd.concat((df_sub_new2, pd.DataFrame([row])), ignore_index=True)
print(cnt)        
print(df_sub_new2.shape)
print(df_sub_new2.head())

1143
(1500, 15)
                 0  1  2  3  4  5  6  7  8  9  10 11 12 13 14
0  00018696_000.png  0  0  0  1  0  0  0  0  0  0  0  0  0  0
1  00008473_002.png  0  0  0  0  0  0  0  0  0  0  1  0  0  0
2  00008473_008.png  0  0  0  0  0  0  0  0  0  0  0  0  1  0
3  00008473_011.png  0  0  0  1  0  0  0  0  0  0  0  1  0  0
4  00005872_001.png  0  0  0  1  1  0  0  0  0  0  0  0  0  0


In [31]:
for i in range(1,15):
    print(df_sub_new2[i].sum(), df_sub[i].sum())

181 181
44 44
197 197
342 342
100 100
106 106
23 23
83 83
71 71
32 32
32 32
31 31
62 62
7 7


In [33]:
df_val_column = pd.DataFrame()
for idx, row in df_val.iterrows():
    row['image_half'] = row[0].split("/")[-1]
    df_val_column = pd.concat((df_val_column, pd.DataFrame([row])),  ignore_index=True)
df_val_column.head()

0  1  2  3  4  5  6  7  8  9  10  11  12  13  14  \
0  images_012/00028178_000.png  0  0  0  0  0  0  0  0  0   0   0   0   0   0   
1  images_012/00030605_000.png  0  0  0  1  0  0  0  0  0   0   0   0   0   0   
2  images_005/00011297_000.png  0  0  0  0  0  0  0  0  0   0   0   0   0   0   
3  images_005/00011297_001.png  0  0  0  0  0  0  0  0  0   0   0   0   0   0   
4  images_008/00016540_000.png  0  0  0  0  0  0  0  0  0   0   0   0   0   0   

         image_half  
0  00028178_000.png  
1  00030605_000.png  
2  00011297_000.png  
3  00011297_001.png  
4  00016540_000.png

In [35]:
df_val_column.shape
file_list = df_sub_new2[0].to_list()
df_val_final = df_val_column[df_val_column['image_half'].isin(file_list)]
print(df_val_final.shape)
df_val_final.head()

(1500, 16)


0  1  2  3  4  5  6  7  8  9  10  11  12  13  \
5   images_009/00018696_000.png  0  0  0  1  0  0  0  0  0   0   0   0   0   
8   images_004/00008473_002.png  0  0  0  0  0  0  0  0  0   0   1   0   0   
14  images_004/00008473_008.png  0  0  0  0  0  0  0  0  0   0   0   0   1   
17  images_004/00008473_011.png  0  0  0  1  0  0  0  0  0   0   0   1   0   
24  images_003/00005872_001.png  0  0  0  1  1  0  0  0  0   0   0   0   0   

    14        image_half  
5    0  00018696_000.png  
8    0  00008473_002.png  
14   0  00008473_008.png  
17   0  00008473_011.png  
24   0  00005872_001.png

In [37]:
df_val_final = df_val_final.drop(columns=['image_half'])
df_val_final.shape

(1500, 15)

In [38]:
df_val_final.head()

0  1  2  3  4  5  6  7  8  9  10  11  12  13  14
5   images_009/00018696_000.png  0  0  0  1  0  0  0  0  0   0   0   0   0   0
8   images_004/00008473_002.png  0  0  0  0  0  0  0  0  0   0   1   0   0   0
14  images_004/00008473_008.png  0  0  0  0  0  0  0  0  0   0   0   0   1   0
17  images_004/00008473_011.png  0  0  0  1  0  0  0  0  0   0   0   1   0   0
24  images_003/00005872_001.png  0  0  0  1  1  0  0  0  0   0   0   0   0   0

In [39]:

df_val_final.to_csv("nih_val_short2.csv", index=False, header=False, sep=" ")

In [27]:
df_sub.shape

(1996, 15)